import pandas as pd
import csv

configfile: "../config/config.yaml"

samples = pd.read_csv(config["samples_table"], sep="\t").to_dict("records")
groups = sorted(set(s["group"] for s in samples))
samples_by_group = {
    g: [s["sample_id"] for s in samples if s["group"] == g]
    for g in groups
}
sample_ids = [str(s["sample_id"]) for s in samples]
cram_paths = dict(zip(sample_ids, [s["cram_path"] for s in samples]))
sample_sizes = dict(zip(sample_ids, [s["sample_size"] for s in samples]))
ref_names = list(config["bwa_refs"].keys())
ref_pairs = [(q, t) for q in ref_names for t in ref_names if q != t]
panther_species = list(config["panther_input_fastas"].keys())

with open("pool_sizes.csv", "w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    for key, value in sample_sizes.items():
        writer.writerow([key, value])

wildcard_constraints:
    group="[PW]"

rule all:
    input:
        expand("results/bwa/{ref_name}/{group}.bam.bai", group=groups, ref_name=ref_names),
        expand("results/bwa/{ref_name}/{group}.bed", group=groups, ref_name=ref_names),
        expand("results/minimap2/{query}_vs_{target}.paf", zip, query=[p[0] for p in ref_pairs], target=[p[1] for p in ref_pairs])

rule panther_all:
    input:
        expand("results/panther/{species}/hmmsearch/batch_{batch}.tblout",
               species=panther_species,
               batch=range(1, config["panther_batches"] + 1))

rule orthofinder_all:
    input:
        "results/orthofinder/Orthogroups.tsv"

rule featurecounts_all:
    input:
        expand("results/featurecounts/{species}_expressed_genes.txt",
               species=panther_species)

rule degenotate_all:
    input:
        expand("results/degenotate/{species}/degeneracy-all-sites.bed",
               species=panther_species)

rule dnds_all:
    input:
        "results/dnds/yn_results.txt"

include: "rules/kmc.smk"
include: "rules/panther.smk"
include: "rules/orthofinder.smk"
include: "rules/featurecounts.smk"
include: "rules/degenotate.smk"
include: "rules/vg_diversity.smk"
include: "rules/dnds.smk"
include: "rules/sourmash.smk"
include: "rules/msmc2.smk"
include: "rules/svim.smk"

rule vg_diversity_all:
    input:
        expand("results/vg/{variant}_vs_{backbone}/{ID}/frequency/{site}/grenedalf_results_frequency.csv",
            variant=[config["vg_ref_variant"]],
            backbone=[config["vg_ref_backbone"]],
            ID=sample_ids,
            site=["cds"]),
        expand("results/vg/{variant}_vs_{backbone}/fst/{site}/grenedalf_results_{window}_fst.csv",
            variant=[config["vg_ref_variant"]],
            backbone=[config["vg_ref_backbone"]],
            window=["interval", "genome"],
            site=["cds", "four", "zero"]),
        expand("results/vg/{variant}_vs_{backbone}/{ID}/diversity/{site}/grenedalf_results_{window}_diversity.csv",
            variant=[config["vg_ref_variant"]],
            backbone=[config["vg_ref_backbone"]],
            window=["interval", "genome"],
            ID=sample_ids,
            site=["cds", "four", "zero"]),
        expand("results/vg/{variant}_vs_{backbone}/{ID}/{ID}.mpileup",
            variant=[config["vg_ref_variant"]],
            backbone=[config["vg_ref_backbone"]],
            ID=sample_ids),
        expand("results/vg/{variant}_vs_{backbone}/{ID}/idxstats.txt",
            variant=[config["vg_ref_variant"]],
            backbone=[config["vg_ref_backbone"]],
            ID=sample_ids)

rule sourmash_all:
    input:
        "results/sourmash/mutation_rate_{s}_vs_{t}.txt".format(
            s=config["sourmash_s"], t=config["sourmash_t"]),
        expand("results/sourmash/{fasta}.sig", fasta=config["sourmash_fastas"].keys())

rule msmc2_all:
    input:
        expand("results/msmc2/{variant}_vs_{backbone}/msmc2.final.txt",
               variant=[config["vg_ref_variant"]],
               backbone=[config["vg_ref_backbone"]])

rule svim_all:
    input:
        expand("results/svim/{variant}_vs_{backbone}/variants.vcf",
               variant=[config["vg_ref_variant"]],
               backbone=[config["vg_ref_backbone"]])
