---
title: "R Notebook"
output: html_notebook
---

# clean slate

```{r}
rm(list = ls())
gc()
.rs.restartR(clean = TRUE)
```

```{r}
library(ggplot2)
library(tidyverse)
library(data.table)

today <- Sys.Date()
```

# sift interproscan output

```{r}

part1 <- fread("../../resources/interproscan/iprscan5-R20260721-003940-0554-50156080-p1m.tsv")

part2 <- fread("../../resources/interproscan/iprscan5-R20260721-003958-0335-42354918-p2m.tsv")

interproscan_results <- rbind(part1, part2)

panther_results <- interproscan_results %>% 
  filter(V4 == "PANTHER") %>%
  filter(!str_detect(V6, "POLYMERASE")) %>%
  filter(!str_detect(V6, "TRANSPOSASE")) %>%
  filter(!str_detect(V6, "DUF"))

```
# dotplots

## haplotype 1 vs primary

```{r}
# ---- 1. Read PAF ----
paf_cols <- c("qname", "qlen", "qstart", "qend", "strand",
              "tname", "tlen", "tstart", "tend",
              "nmatch", "alen", "mapq")

paf <- read_tsv("../../resources/dotplots/hap1_vs_primary.paf", col_names = FALSE, col_types = cols(.default = "c"))
paf <- paf[, 1:12]                      # keep only the 12 mandatory columns
colnames(paf) <- paf_cols

paf <- paf %>%
  mutate(across(c(qlen, qstart, qend, tlen, tstart, tend, nmatch, alen, mapq), as.numeric),
         pident = nmatch / alen)        # approximate % identity per alignment block

# ---- 2. Filter low alignment blocks ----
paf_f <- paf %>%
  filter(alen >= 1000, mapq >= 1)

# ---- 3. Orient reverse-strand alignments for correct diagonal direction ----
paf_plot <- paf_f %>%
  mutate(
    tstart_plot = if_else(strand == "-", tend, tstart),
    tend_plot   = if_else(strand == "-", tstart, tend)
  )

# ---- 4. Simple whole-genome dotplot ----
ggplot(paf_plot) +
  geom_segment(aes(x = qstart, xend = qend,
                    y = tstart_plot, yend = tend_plot,
                    color = strand),
               linewidth = 0.6) +
  scale_color_manual(values = c("+" = "steelblue", "-" = "firebrick")) +
  labs(x = "Query (bp)", y = "Target (bp)",
       title = "minimap2 whole-genome alignment",
       color = "Strand") +
  theme_minimal() +
  theme(panel.grid.minor = element_blank())

## 5. specific scaffold
for(tscaf in paste0("scaffold_", 1:51)){
  print(
    
  ggplot(subset(paf_plot, qname == "scaffold_25" & tname == tscaf)) +
  geom_segment(aes(x = qstart, xend = qend,
                    y = tstart_plot, yend = tend_plot,
                    color = strand),
               linewidth = 0.6) +
  scale_color_manual(values = c("+" = "steelblue", "-" = "firebrick")) +
  labs(x ="Haplotype 1, scaffold 25 (bp)", y = paste0("Primary ", tscaf, " (bp)"),
       title = "minimap2 whole-genome alignment",
       color = "Strand") +
  theme_minimal() +
  theme(panel.grid.minor = element_blank())
  
  )
}

```

## haplotype 1 and haplotype 2

check if myb cluster also present on haplotype 2

```{r}
paf_cols <- c("qname", "qlen", "qstart", "qend", "strand",
              "tname", "tlen", "tstart", "tend",
              "nmatch", "alen", "mapq")

paf <- read_tsv("../../resources/dotplots/hap2_vs_hap1.paf", col_names = FALSE, col_types = cols(.default = "c"))
paf <- paf[, 1:12]                      # keep only the 12 mandatory columns
colnames(paf) <- paf_cols

paf <- paf %>%
  mutate(across(c(qlen, qstart, qend, tlen, tstart, tend, nmatch, alen, mapq), as.numeric),
         pident = nmatch / alen)        # approximate % identity per alignment block

# ---- 2. Filter low alignment blocks ----
paf_f <- paf %>%
  filter(alen >= 1000, mapq >= 1)

# ---- 3. Orient reverse-strand alignments for correct diagonal direction ----
paf_plot <- paf_f %>%
  mutate(
    tstart_plot = if_else(strand == "-", tend, tstart),
    tend_plot   = if_else(strand == "-", tstart, tend)
  )

# ---- 4. Simple whole-genome dotplot ----
ggplot(subset(paf_plot, tname == "scaffold_25" & qname == "scaffold_2")) +
  geom_segment(aes(x = qstart, xend = qend,
                    y = tstart_plot, yend = tend_plot,
                    color = strand),
               linewidth = 0.6) +
  scale_color_manual(values = c("+" = "steelblue", "-" = "firebrick")) +
  geom_hline(yintercept = 10964369) +
  geom_hline(yintercept = 12046688) +
  labs(x = "White (i.e. Haplotype 2), scaffold 2 (bp)", y = "Pink (i.e. Haplotype 1), scaffold 25 (bp)",
       title = "minimap2 whole-genome White vs Pink\nMyb cluster delinated with lines",
       color = "Strand") +
  theme_minimal() +
  theme(panel.grid.minor = element_blank())

ggsave(paste0("../../results/by-date/", today, "/dotplot_hap2_scaffold2_vs_hap1_scaffold_25.pdf"))


```

## haplotype 1 and 2

Code and alignment from yaniv

```{r}
x <- read_tsv("../../resources/dotplots/hap1_vs_hap2.1to1.coords", col_names = c("S1","E1" ,"S2","E2","LEN_1","LEN_2","PCT_IDY","LEN_R","LEN_Q","COV_R","COV_Q","REF_TAG","QUERY_TAG"))

make_plot <- function(scaffold){
  queery <- x|>
    filter(REF_TAG == scaffold) |>
    group_by(QUERY_TAG) |>
    summarise(tot = sum(LEN_2))|>
    mutate(prop = tot / sum(tot))|>
    filter(prop > 0.02)|>
    pull(QUERY_TAG)
  ggplot(x|> filter(REF_TAG==scaffold,QUERY_TAG %in% queery),
         aes(x = S1, xend = E1, y = S2, yend = E2 , color = QUERY_TAG))+
    geom_segment(linewidth = 2)+
    geom_vline(xintercept = 57821464) + 
    geom_vline(xintercept = 57828110) + 
    theme_minimal()+
    theme(axis.line = element_line(color = "black"))+
    ggtitle(scaffold)
}

make_plot("scaffold_1")
ggsave(paste0("../../results/by-date/", today, "/dotplot_scaffold1_g8317.pdf"))

scaffolds <- paste0("scaffold_", 1:36)

pdf(
  paste0("../../results/by-date/", today, "/hap1_vs_hap2_scaffolds_1_to_18.pdf"),
  width = 10,
  height = 7
)

purrr::walk(scaffolds, \(scaffold) {
  print(make_plot(scaffold))
})

dev.off()
```
