# --- KMC ---
kmc_k: 31
kmc_mincount: 10
kmc_maxcount: auto

# --- fastp ---
fastp_unqual_limit: 40
fastp_qual_thresh: 20
fastp_window_length: 4
fastp_min_len: 31
fastp_n_base_limit: 5

# --- kmc_filter: how to build group-specific k-mer set ---
subtract_groups: true
min_group_count: 0

# --- metaSPAdes ---
metaspades_kmers: "auto"
metaspades_mem: 200
metaspades_tmp_dir: "/tmp"

# --- kmc_tools complex params ---
kmc_intersect_depth: 100

# --- samples ---
samples_table: "../config/samples.tsv"

# --- general ---
conda_prefix: "envs"
