# --- KMC ---
kmc_k: 31
kmc_mincount: 10
kmc_maxcount: auto

# --- fastp ---
fastp_unqual_limit: 40
fastp_qual_thresh: 20
fastp_window_length: 4
fastp_min_len: 31
fastp_n_base_limit: 5

# --- kmc_tools complex params ---
kmc_intersect_depth: 1000000

# --- BWA ---
bwa_refs:
  hap1: "../resources/reference/hap1.fasta"
  hap2: "../resources/reference/hap2.fasta"
  hap1_rc: "../resources/reference/hap1_rc.fasta"
  hap2_rc: "../resources/reference/hap2_rc.fasta"
bwa_count_threshold: 40
bwa_k: 31
bwa_A: 1
bwa_B: 100
bwa_O: 100
bwa_E: 100
bwa_L: 100
bwa_T: 31
bwa_merge_distance: 1000

# --- minimap2 ---
minimap2_f: 0.02

# --- PANTHER HMM search ---
panther_input_fastas:
  hap1: "../resources/annotation/LPJR3B1_scaf_hap1_braker_aa.fasta"
  hap2: "../resources/annotation/LPJR3B1_scaf_hap2_braker_aa.fasta"
panther_batches: 3000
panther_hmmsearch_evalue: 0.001
panther_hmmsearch_dome: 1e-8
panther_hmmsearch_ince: 0.001
panther_hmmsearch_incdome: 1e-8

# --- OrthoFinder ---
orthofinder_external_proteomes:
  arabidopsis: "../resources/proteomes/arabidopsis_thaliana.faa"

# --- featureCounts ---
featurecounts_annotations:
  hap1: "../resources/annotation/hap1.gff3"
  hap2: "../resources/annotation/hap2.gff3"
featurecounts_bams:
  hap1:
    - "../resources/annotation/rna_hap1/LP1_MAPQFiltered_CoordSort.bam"
    - "../resources/annotation/rna_hap1/LP2_MAPQFiltered_CoordSort.bam"
    - "../resources/annotation/rna_hap1/LP3_MAPQFiltered_CoordSort.bam"
    - "../resources/annotation/rna_hap1/LP4_MAPQFiltered_CoordSort.bam"
    - "../resources/annotation/rna_hap1/LP5_MAPQFiltered_CoordSort.bam"
    - "../resources/annotation/rna_hap1/LP6_MAPQFiltered_CoordSort.bam"
  hap2:
    - "../resources/annotation/rna_hap2/LP1_MAPQFiltered_CoordSort.bam"
    - "../resources/annotation/rna_hap2/LP2_MAPQFiltered_CoordSort.bam"
    - "../resources/annotation/rna_hap2/LP3_MAPQFiltered_CoordSort.bam"
    - "../resources/annotation/rna_hap2/LP4_MAPQFiltered_CoordSort.bam"
    - "../resources/annotation/rna_hap2/LP5_MAPQFiltered_CoordSort.bam"
    - "../resources/annotation/rna_hap2/LP6_MAPQFiltered_CoordSort.bam"
featurecounts_gff_feature: "Parent"
featurecounts_paired: true

# --- vg graph genome & diversity ---
vg_ref_backbone: "hap1"
vg_ref_variant: "hap2"
paftools_call_L: 1000
paftools_call_q: 20
samtools_mpileup_Q: 20
samtools_mpileup_q: 20
grenedalf_window_width: 50000
grenedalf_filter_sample_min_read_depth: 5
grenedalf_window_average_policy: "valid-loci"
grenedalf_filter_sample_min_count: 2
grenedalf_min_map_qual: 20
grenedalf_min_base_qual: 20
grenedalf_subsample_max_read_depth: 500
grenedalf_fst_method: "unbiased-hudson"

# --- sourmash ---
sourmash_fastas:
  hap1: "../resources/reference/hap1.fasta"
  hap2: "../resources/reference/hap2.fasta"
sourmash_sketch_modes:
  hap1: "standard"
  hap2: "multiplicity"
sourmash_k: 31
sourmash_scaled: 10000
sourmash_s: "hap1"
sourmash_t: "hap2"
sourmash_estimator: "r_pc"

# --- svim-asm ---
svim_chunk_size: 200000000
svim_minimap_x: "asm10"
svim_samtools_sort_m: "1G"
svim_reference_gap_tolerance: 2000000
svim_max_sv_size: 25000000

# --- MSMC2 ---
msmc2_binary: "/global/scratch/users/milesroberts/conda/msmc2/bin/msmc2_Linux"
msmc2_generate_multihetsep: "/global/home/users/milesroberts/bin/msmc-tools/generate_multihetsep.py"
msmc2_p: "2*1+15*1+1*2"

# --- BRAKER3 RNA-seq annotation ---
minimap2_braker:
    backbone: "../resources/reference/hap1.fasta"
    variant: "../resources/reference/Linanthus_parryae.fasta"
rna_sra_accessions:
  - "SRR29348131"
  - "SRR29348132"
  - "SRR29348133"
  - "SRR29348134"
  - "SRR29348135"
braker_genomes:
  LPJR3B1_scaf: "../resources/reference/LPJR3B1_scaf.fasta"
braker_species: "lepto"
braker_container: "docker://teambraker/braker3:v3.1.1"

# --- AnchorWave gene-anchored whole-genome alignment ---
anchorwave_backbone: "hap1"
anchorwave_variant: "hap2"
anchorwave_minimap_k: 12
anchorwave_minimap_p: 0.4
anchorwave_minimap_n: 20

# --- dn/ds ---
dnds_aa_fasta: "../config/dnds/OG0001281_myb_cluster_only_aa.fa"
dnds_cds_fasta: "../config/dnds/OG0001281_myb_cluster_only_cds.fa"
dnds_yn00_ctl: "../config/dnds/yn00.ctl"

# --- samples ---
samples_table: "../config/samples.tsv"
