# --- KMC ---
kmc_k: 51
kmc_mincount: 10
kmc_maxcount: auto

# --- fastp ---
fastp_unqual_limit: 40
fastp_qual_thresh: 20
fastp_window_length: 4
fastp_min_len: 31
fastp_n_base_limit: 5

# --- kmc_filter: how to build group-specific k-mer set ---
subtract_groups: true
min_group_count: 0

# --- metaSPAdes ---
metaspades_kmers: "auto"
metaspades_mem: 200
metaspades_tmp_dir: "/tmp"

# --- kmc_tools complex params ---
kmc_intersect_depth: 100

# --- BWA ---
bwa_ref: "../resources/reference/LPJR3B2_scaffolds_final.fa"
bwa_count_threshold: 40
bwa_k: 50
bwa_A: 1
bwa_B: 100
bwa_O: 100
bwa_E: 100
bwa_L: 100
bwa_T: 50

# --- samples ---
samples_table: "../config/samples.tsv"
