executor: slurm
jobs: 100000

default-resources:
  slurm_account: "co_moilab"
  #slurm_partition: "savio3_htc"
  #slurm_qos: "savio_lowprio"
  slurm_partition: "savio4_htc"
  slurm_qos: "moilab_htc4_normal"
  mem_mb: 0
  mem_mb_per_cpu: 0
  disk_mb: 0
  cpus_per_task: 1
  mem_per_cpu: 0
  ntasks: 1
  threads: 1
  runtime: 60

set-threads:
   samtools_fastq: 4
   fastp: 8
   kmc_count: 8
   kmc_intersect_group: 4
   kmc_subtract: 4
   bwa_mem: 8
   kmc_filter_reads: 4
   combine_group_reads: 1
   panther_hmmsearch: 8
   orthofinder_run: 16
   featurecounts_run: 4
   degenotate_run: 4
   minimap2_asm_paf: 16
   vg_autoindex: 8
   vg_giraffe: 12
   vg_surject: 8
   samtools_sort_index_vg: 8
   grenedalf_diversity: 2

set-resources:
  samtools_fastq:
    cpus_per_task: 4
    runtime: 60
  fastp:
    cpus_per_task: 8
    runtime: 60
  kmc_count:
    cpus_per_task: 8
    runtime: 120
  kmc_intersect_group:
    cpus_per_task: 4
    runtime: 120
  kmc_subtract:
    cpus_per_task: 4
    runtime: 120
  bwa_mem:
    cpus_per_task: 8
    runtime: 120
  kmc_filter_reads:
    cpus_per_task: 4
    runtime: 60
  combine_group_reads:
    cpus_per_task: 4
    runtime: 60
  bcalm:
    cpus_per_task: 4
    runtime: 300
  panther_hmmsearch:
    cpus_per_task: 8
    runtime: 20
  orthofinder_stage:
    runtime: 10
  orthofinder_stage_external:
    runtime: 10
  orthofinder_run:
    slurm_account: "co_moilab"
    slurm_partition: "savio4_htc"
    slurm_qos: "moilab_htc4_normal"
    cpus_per_task: 16
    runtime: 1440
  featurecounts_run:
    cpus_per_task: 4
    runtime: 60
  degenotate_run:
    cpus_per_task: 8
    runtime: 120
  minimap2_asm_paf:
    cpus_per_task: 16
    runtime: 120
  vg_autoindex:
    runtime: 240
  vg_giraffe:
    cpus_per_task: 16
    runtime: "max(4*input.size_mb/1024, 20)"
  vg_surject:
    cpus_per_task: 8
    runtime: "max(4*input.size_mb/1024, 20)"
  samtools_sort_index_vg:
    cpus_per_task: 8
    runtime: 360
  picard_reorder_sam:
    runtime: 1440
  samtools_index_reordered:
    runtime: 360
  grenedalf_diversity:
    cpus_per_task: 4
    runtime: 360
